Added tooltips for all parts of the Create Commons Form except for ending date, as of this commit ending date does not yet exist
ucsb-cs156-f23/proj-happycows-f23-5pm-2 pull request #22
Opened 2023-11-17 23:52 UTC by ChinDandekar

## Overview

In this PR, I added tooltips for all parts of the Create Commons Form except for ending date. This page is only accessible to Admins, and allows any admin creating a new common to see what each field in the form means when they hover their mouse over that field.

## Screenshots
<img width="1440" alt="Screenshot 2023-11-17 at 3 48 43 PM" src="https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-2/assets/102712851/f81b1672-7883-4ca8-83a7-db600fec49e7">
<img width="517" alt="Screenshot 2023-11-17 at 3 48 56 PM" src="https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-2/assets/102712851/25024ceb-d2bb-4ff2-be27-dde51762dea0">
<img width="535" alt="Screenshot 2023-11-17 at 3 49 03 PM" src="https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-2/assets/102712851/5680be46-c4c5-4410-b31a-36b20b1a7715">
<img width="527" alt="Screenshot 2023-11-17 at 3 49 08 PM" src="https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-2/assets/102712851/7b5df4bf-47e0-405e-b245-ae15d3d9069b">
<img width="382" alt="Screenshot 2023-11-17 at 3 49 13 PM" src="https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-2/assets/102712851/35cec7cb-1b7c-444c-a761-2597e580c5dd">
<img width="358" alt="Screenshot 2023-11-17 at 3 49 19 PM" src="https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-2/assets/102712851/9e79a492-243c-486f-8176-3b5d3ed8b688">
<img width="382" alt="Screenshot 2023-11-17 at 3 49 24 PM" src="https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-2/assets/102712851/2094adeb-c0ef-48d2-be89-fd60ec5b5aaf">
<img width="357" alt="Screenshot 2023-11-17 at 3 49 28 PM" src="https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-2/assets/102712851/2873bf19-4e83-442c-90e9-8d3decfbb2d9">
<img width="258" alt="Screenshot 2023-11-17 at 3 49 36 PM" src="https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-2/assets/102712851/726d4a52-40d2-4050-a1da-ce731d54edd6">

## Feedback Request
Please give suggestions on the following:
- The way this is implemented is the best I can think of. Is it acceptable?

## Validation
1. Download this branch.
2. Run the project backend and frontend locally.
3. Log in as an Admin and go to Admin -> Create Commons.
4. Test this function.

For some reason my personal deployment isn't working, I'll work on that and put the link on this PR when it gets working.

## Linked Issues

Linked with #18 

Closes #1

2023-11-18 19:15 UTC, GlassBricks requested changes

2023-11-18 19:15 UTC, GlassBricks commented on frontend/package-lock.json
`package-lock.json` should probably not be included in this PR.
This seems to be part of the last commit; could you revert it (or drop the commit and force-push)?

2023-11-19 00:50 UTC, chriscerie commented on frontend/package-lock.json
It's much worse to develop with an updated dependency set, commit those changes, then discard the lockfile diff. The team should be working with consistent dependency trees or you risk running into "it worked on my machine" situations, even if they're only patch bumps. The better approach here would be to suggest using `npm ci` for the future to preserve lock versions.

2023-11-20 03:04 UTC, pconrad commented on frontend/package-lock.json
Chris, I think the point is that there shouldn't be a commit to package-lock.json unless there has been a change to package.json, which in this case, there has not.  I agree with @GlassBricks : package-lock.json should not be a part of this PR.

2023-11-20 03:05 UTC, pconrad commented on frontend/package-lock.json
@ChinDandekar do you know how to do that git magic to get rid of the changes to package-lock.json while keeping your other changes intact?  If so, please do it.  If not, let me know, and I'll walk you through it.

2023-11-20 03:16 UTC, pconrad requested changes
Please remove package-lock.json from the PR.

One easy way to do that is this:

```
git checkout chinmay-explain-create-commons-page
git pull origin chinmay-explain-create-commons-page
git fetch
```

That gets you on the branch, and updates your branch plus the local value of where origin/main points.

Then do this: this keeps the files on the file system the same (that's what --soft means here) but resets the pointer of your branch to where main is on Github, so that you have a starting point to rebuild your commit history:

```
git reset --soft origin/main
git status
```

Now you'll see the files that are changed from main, which includes both 
* src/main/components/Commons/CommonsForm.js
* frontend/package-lock.json

Do a new commit but ONLY add the .js file:
```
git add src/main/components/Commons/CommonsForm.js
git commit -m "cd - add tooltips to CommonsForm.js"
```

Then you'll need to do a force push because you did a reset on the branch pointer:

```
git push origin chinmay-explain-create-commons-page -f
```

2023-11-20 03:51 UTC, chriscerie commented on frontend/package-lock.json
@pconrad Whether the lockfile change should be committed or not isn't my point. The lockfile is meaningless if the local development and testing environment deviates from it. If the OP had only reverted the commit and nothing else, their local build would deviate from everyone else's. A better solution is to suggest rebuilding dependencies using `npm ci` so this issue doesn't come up again. With or without reverting that lockfile diff first (and any possible security updates that went with the patch bumps) is aside from my point, but either way simply suggesting to revert the change isn't the answer.

In this case the chances of this mattering is small as it was only 2 patch bumps. But for the sake of better software practices (see axios that shipped a [buggy release](https://github.com/axios/axios/issues/5038) and broke downstream consumers that did not pin dependencies properly), I hope this pattern changes.

2023-11-21 20:55 UTC, pconrad commented on frontend/package-lock.json
@chriscerie You raise some interesting points; let's discuss those (you and me) by email.   

In terms of this PR, I think @GlassBricks 's feedback was appropriate.   

@ChinDandekar please just focus on removing `package-lock.json` from the PR (I'm making a guide right now with two ways to do that; I'll link to that when it's done.)   You can disregard the rest of the thread; if something comes out of it from my discussions with @chriscerie in terms of modifying our suggested development process for frontend code,  I'll let the entire class know.

2023-11-21 23:11 UTC, GlassBricks commented on frontend/package-lock.json
If I may comment:
My point in asking to revert the change is, while updating packages can be a good idea, that should be done as a separate PR, not tagged along in here.
Perhaps more complete instructions would be to also run `npm install` after reverting the change, so the package versions sync up.

2023-11-24 21:20 UTC, pconrad approved these changes
LGTM

2023-11-24 21:24 UTC, merged