Implemented gameInProgress() under Commons entity, and tests.
ucsb-cs156-f23/proj-happycows-f23-5pm-2 pull request #37
Opened 2023-11-26 14:30 UTC by alexkxu

## Overview
In this PR, issue #20 is addressed. A preliminary implementation of gameInProgress() under the Commons entity is implemented alongside tests covering true and false outputs. The function returns true if today's date is >= start date, and <= last day.

Note that this PR relies on a parameter implemented in #18, and of writing, is under development by @amgadhawari. Temporarily, all I have done regarding this is include a `private LocalDateTime lastDate` variable in the Commons class. Due to this, the changes in this PR are obviously subject to change if merge conflicts arise with #18.

Also, do note that "Acceptance Criteria for Future Issues" under the linked issue #11 are not addressed in this PR.

## Feedback Request (Optional)
Please give suggestions on the following:
- Using LocalDateTime libraries might not be optimal in terms of efficiency when comparing dates (used in four statements), but is a relatively safe option. Could be room for optimization.

## Future Possibilities (Optional)

Some possible points could be:
- This is the enables the "Acceptance Criteria for Future Issues" under #11. These include: add logic to the backends of various jobs that operate on all commons (MilkTheCows, UpdateCowHealth, InstructorReports) where it iterates over the commons. Skip over commons where gameInProgress() returns false. 

## Validation (Optional)
1. Download this branch.
2. Run the project.
3. Go to this page.
4. Test this function.

## Tests
- [ ] Backend Unit tests (`mvn test`) pass
- [ ] Backend Test coverage (`mvn test jacoco:report`) 100%
- [ ] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [ ] Frontend Unit tests (`npm test`) pass
- [ ] Frontend Test coverage (`npm run coverage`) 100%
- [ ] Frontend Mutation tests (`npx stryker run`) 100% 
- [ ] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues
Closes #20
Linked to #11

2023-11-26 18:44 UTC, alexkxu commented
never mind, my updates to the dependencies nuked a test in the starter code, will continue to debug.

2023-11-26 19:40 UTC, alexkxu commented
not sure what's causing the problem here, all Jacoco coverage checks are being met locally.

2023-11-27 18:39 UTC, hancheng-li submitted a review, later dismissed
Other than the commented out code, LGTM

2023-11-28 17:24 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
> +        //             && (todayDateTime.isBefore(lastDate) || todayDateTime.equals(lastDate)) );
https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2023-11-28 17:25 UTC, pconrad requested changes
https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2023-11-28 17:25 UTC, pconrad commented on src/test/java/edu/ucsb/cs156/happiercows/entities/CommonsTests.java
> +// import org.mockito.MockedStatic;
https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2023-11-28 17:25 UTC, pconrad commented on src/test/java/edu/ucsb/cs156/happiercows/entities/CommonsTests.java
> +}
https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2023-11-28 22:55 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
> +    private LocalDateTime lastDate; // subject to change, see issue #18, linked to #11
this comment won't make any sense in the final production repo, so let's remove this and make it as a comment on the PR instead.

2023-11-29 17:47 UTC, pconrad approved these changes
LGTM

2023-11-30 04:09 UTC, merged